### ISSUE TITLE
Let box!?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [atifaziz/Boxing#2]
0. `Box<T> : IBox<T>`
1. `readonly struct Box<T>`
2. `RefBox` https://github.com/scalaz/scalaz-zio/blob/master/core/shared/src/main/scala/scalaz/zio/Ref.scala ? `Interlocker`? Why `class Interlocker`? Why not struct?
3. Ref return:
```
IRefApply<T>
{
    ref<T> Invoke()
}
public Box(TRefApply<T> valueRef) where TRefApply<T> : IRefApply<T>
  => this.valueRef = valueRef;

public ref T Value = ref valueRef.Invoke();
```

**Comment by atifaziz** [comment]
I'm not sure about what you are saying here. Care to clarify/expand?

**Comment by dzmitry-lahoda** [comment]
3. There is new design in C#(thanks to all `ref` suff and `Unsafe`). In this design it is possible to manage memory manually and pass by `ref`.  But ref cannot be stored without copy. So I want to have index to `Memory`(or array or circular buffer) stored behind `IRefApply` call(which is struct)  to avoid `delegate` overhead. Box also struct to avoid overhead and because struct cannot have `ref` into fields I need ref into manually managed memory. So there should be another ref like Box to state `boxing any value`. Because I cannot box large structures in sane manner.

2. I consider `Ref.Scala` to be a box of some kind. Could `Interlocker` be named as `AtomicBox` or like? Could `AtomicBox` be structure? To have common name pattern? Also it could use some GC allocated object imlementing `IRefApply` to get ref. Or (if works), as it stores only value it could Unsafe cast it into itself and pass self as ref. So Interlocker maybe can be struct.

1.  Mark as readonly, I guess it is right for designs. Will not hurt? Right?

0. What is API fox boxes? Any other boxes to have, so interface?

**Comment by dzmitry-lahoda** [comment]
1. `Box<T< : IBox<out T>`
2. Lazy is : IBox
3. Interlocker : IBox.
4. And `IRefBox` as for ref return.

**Comment by atifaziz** [comment]
> 5\. Mark as readonly, I guess it is right for designs. Will not hurt? Right?

This is done in ee4c0aeebd9d6db5be828b948cab444ae05db732. However, with respect to the rest, I am completely lost as to what you are asking or suggesting even when I re-read months later. I will close this issue now but happy to re-open if you can provide more clarity. Thanks.
